import SSAO1Pass from "./SSAO";
import GBufferPass from "./GBufferPass";
import BlurPass from "./GaussianBlur";
import CompositePass from "./CompositePass";
import ContourPass from "./ContourPass";
import DrawBufferPass from "./DrawBufferPass";
import { InstancedFiberGroup } from "./InstancedFiber";
import { GeometryInstanceContainer } from "../types";
import { Color, Group, OrthographicCamera, PerspectiveCamera, Scene, WebGLMultipleRenderTargets, WebGLRenderer, WebGLRenderTarget } from "three";
import { Pane } from "tweakpane";
export interface AOSettings {
    aoradius1: number;
    blurradius1: number;
    aothreshold1: number;
    aofalloff1: number;
    aoradius2: number;
    blurradius2: number;
    aothreshold2: number;
    aofalloff2: number;
}
declare class SimulariumRenderer {
    gbufferPass: GBufferPass;
    ssao1Pass: SSAO1Pass;
    ssao2Pass: SSAO1Pass;
    blur1Pass: BlurPass;
    blur2Pass: BlurPass;
    compositePass: CompositePass;
    contourPass: ContourPass;
    drawBufferPass: DrawBufferPass;
    gbuffer: WebGLMultipleRenderTargets;
    private hitTestHelper;
    blurIntermediateBuffer: WebGLRenderTarget;
    ssaoBuffer: WebGLRenderTarget;
    ssaoBuffer2: WebGLRenderTarget;
    ssaoBufferBlurred: WebGLRenderTarget;
    ssaoBufferBlurred2: WebGLRenderTarget;
    private parameters;
    private boundsNear;
    private boundsFar;
    constructor();
    applyAO(ao: AOSettings): void;
    setupGui(gui: Pane): void;
    setBackgroundColor(color: Color): void;
    setFollowedInstance(instance: number): void;
    hitTest(renderer: WebGLRenderer, x: number, y: number): number;
    updateColors(numColors: number, colorsData: Float32Array): void;
    setMeshGroups(instancedMeshGroup: Group, fibers: InstancedFiberGroup, meshTypes: GeometryInstanceContainer[]): void;
    resize(x: number, y: number): void;
    setNearFar(n: number, f: number): void;
    render(renderer: WebGLRenderer, scene: Scene, camera: PerspectiveCamera | OrthographicCamera, target: WebGLRenderTarget | null): void;
}
export default SimulariumRenderer;
