# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: NPM Package
env:
    NODE_VERSION: "14.x"
on:
    push:
        # Sequence of patterns matched against refs/tags
        tags:
            - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{env.NODE_VERSION}}
            - run: npm ci
            - run: npm run lint --if-present
    test:
        name: Unit Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{env.NODE_VERSION}}
            - run: npm ci
            - run: npm test --if-present
    typeCheck:
        name: Type Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{env.NODE_VERSION}}
            - run: npm ci
            - run: npm run typeCheck --if-present
    build:
        needs: [lint, typeCheck, test]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{env.NODE_VERSION}}
            - run: npm ci
            - run: npm run build

    publish-npm:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{env.NODE_VERSION}}
                  registry-url: https://registry.npmjs.org/
            - run: npm ci
            - run: npm run build
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
